### ISSUE TITLE
我做过三年多的android，开发过上线的项目，想参与一下

### ISSUE THREAD

**Issue by swewjk** [yjjhkyq/doubi#1]

**Comment by yjjhkyq** [comment]
要的，麻烦把你的微信发我下哈

**Comment by swewjk** [comment]
我的微信swewjk



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月12日(周三) 晚上8:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yjjhkyq/doubi] 我做过三年多的android，开发过上线的项目，想参与一下 (Issue #1)




 
要的，麻烦把你的微信发我下哈
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
